### ISSUE TITLE
dati_bollo: dati_beni_servizi.natura: [00429] field is empty while aliquota_iva is zero

### ISSUE THREAD

**Issue by deeper-x** [Truelite/python-a38#33] opened 2023-02-23 16:28 UTC
If you define a document with ```dati_bollo```, adding a document's ```linea``` for it, ```aliquota_iva``` must be 0 (art. 15 del D.P.R. n. 633/1972), as well as ```natura``` need to be set with a code (here N1¹ code) .
We get an error, though:
```sh
$ python main.py 
fattura_elettronica_body.0.dati_beni_servizi.natura: [00429] field is empty while aliquota_iva is zero
```
To reproduce, update your example in [README](https://github.com/Truelite/python-a38#example-code) like that:

1. build a document with dati_bollo in ```DatiGeneraliDocumento```
```python3
body.dati_generali.dati_generali_documento = DatiGeneraliDocumento(
    tipo_documento="TD01",
    divisa="EUR",
    data=datetime.date.today(),
    numero=bill_number,
    causale=["Test billing"],
    dati_bollo=DatiBollo(
        bollo_virtuale="SI",
        importo_bollo="2",
    )
)
```
2. Add a line in invoice, with a ```"Bollo"``` 2€ record, with 0 ```aliquota_iva``` and a ```natura``` code
```python3
...
body.dati_beni_servizi.add_dettaglio_linee(
    descrizione="Bollo", quantita=1, unita_misura="EUR",
    prezzo_unitario="2", aliquota_iva="0.00", natura="N1",
)
```
3. Check out the resulting xml. This is supposed to build nodes like that:
```xml
<DatiBollo>
   <BolloVirtuale>SI</BolloVirtuale> 
   <ImportoBollo>2.00</ImportoBollo>
</DatiBollo>
...
<NumeroLinea>3</NumeroLinea>
    <Descrizione>Bollo</Descrizione>
    <Quantita>1.00</Quantita>
    <UnitaMisura>EUR</UnitaMisura>
    <PrezzoUnitario>2.00</PrezzoUnitario>
    <PrezzoTotale>2.00</PrezzoTotale>
    <AliquotaIVA>0.00</AliquotaIVA>
    <Natura>N1</Natura>
</DettaglioLinee>
...
<DatiRiepilogo>
    <AliquotaIVA>0.00</AliquotaIVA>
    <Natura>N1</Natura>
   <ImponibileImporto>2.00</ImponibileImporto>
   <Imposta>0.00</Imposta>
   <EsigibilitaIVA>I</EsigibilitaIVA>
</DatiRiepilogo>
```
And it works, it's built correctly. But we get an apparently false-negative:
```sh
$ python main.py 
fattura_elettronica_body.0.dati_beni_servizi.natura: [00429] field is empty while aliquota_iva is zero
```
This happens on validation stage, on your example, when you print out if errors occour:
```python3
# file: main.py
if res.errors:
    for e in res.errors:
        print(str(e), file=sys.stderr)
```
The reason is because it expects ```DatiRiepilogo.natura``` to be instantiated, while it's not:
```python3
# file: fattura.py:447
    def validate_model(self, validation):
        super().validate_model(validation)
        if self.aliquota_iva == 0 and self.natura is None: # <--- this check fails
            validation.add_error(
                self._meta["natura"], "field is empty while aliquota_iva is zero", code="00429")
```

To fix it, in fattura.py ```DatiBeniServizi().build_dati_riepilogo``` should be defined ```natura``` var and it has to be passed to the model, like that:
```python3
# file: fattura.py:496
        self.dati_riepilogo = []
        for aliquota, linee in sorted(by_aliquota.items()):
            natura = linee[0].natura # <--- setting new var to pass on DatiRiepilogo() model
            imponibile = sum(linea.prezzo_totale for linea in linee)
            imposta = imponibile * aliquota / 100
            self.dati_riepilogo.append(
                    DatiRiepilogo(
                        aliquota_iva=aliquota, imponibile_importo=imponibile,
                        imposta=imposta, esigibilita_iva="I", natura=natura)) # <-- here we go :)
```
Now it works, keeping to build a valid xml, without any failed validation:
```sh
$ python main.py 
$ ls
bin  include  IT01234567890_00001.xml  lib  lib64  main.py  pyvenv.cfg  README.md  requirements.txt  stubs  tests 
```
  
¹: see https://www.agendadigitale.eu/documenti/esperto-risponde/fattura-elettronica-ecco-come-indicare-il-bollo/

**Comment by spanezz** [comment] 2023-02-23 19:55
Hi, thanks for raising the issue: I tried to reproduce it in a6142f63edfaecd1b9c9b315cb29d5e08db2068c.

Unfortunately, I failed: after calling `build_dati_riepilogo`, natura has indeed been filled. 

If I look at the [build_dati_riepilogo function](https://github.com/Truelite/python-a38/blob/master/a38/fattura.py#L478),  natura is collected in the first part:

```py
        by_aliquota = defaultdict(list)                                                                                     
        for linea in self.dettaglio_linee:                                                                                  
            by_aliquota[(linea.aliquota_iva, linea.natura)].append(linea)                                                   
```

and then used in the second:

```
        for (aliquota, natura), linee in sorted(by_aliquota.items()):                                                       
            # ...
            self.dati_riepilogo.append(   
                    DatiRiepilogo(
                        aliquota_iva=aliquota, imponibile_importo=imponibile,
                        imposta=imposta, esigibilita_iva="I", natura=natura))
```

Would you be able to update [the test I just added](https://github.com/Truelite/python-a38/blob/master/tests/test_fattura.py#L166) so that it can reproduce what your'e observing?

**Comment by deeper-x** [comment] 2023-02-24 09:23
Hi Enrico, I think issue is related to the tag: I'm afraid published version on pypi is not aligned to the origin on GH. 
If you install module via pip like that
```python
python -m pip install a38
```
It fetches:
https://pypi.org/project/a38/

which is v0.1.5, where codebase is not fixed, generating bug I was referring to: [look here](https://github.com/Truelite/python-a38/blob/b6c833d6b8ea55e6b3dd0c3c2de7ac521043a89a/a38/fattura.py#L497)

**Comment by spanezz** [comment] 2023-02-24 12:12
Ah, I see, I'm glad the reason for the issue is worked out.

As soon as I'm done with #32, I guess we can make a new pip release and close this issue. Would that work?

**Comment by deeper-x** [comment] 2023-02-24 12:28
Yeap. Looking forward to get it from pypi. Meanwhile, I'm working with the GH source code, and it works like a charm.
Thank you Enrico! keep it up ;)
Cheers
Alberto

**Closed** 2023-02-24 12:28 UTC
